### ISSUE TITLE
Error in creating workload

### ISSUE THREAD

**Issue by sanjoydanversent** [stax-labs/lib-stax-python-sdk#46]
**Describe the bug**
I'm using python code to create workload from an existing catalogue.
workload_client = StaxClient("workloads")
response = workload_client.CreateWorkload( Name        = workload_name, 
                                                            CatalogueId = catalogue_id, 
                                                            AccountId   = stax_account_id, 
                                                            Region      = region_name,
                                                            Parameters  = workload_parameters, 
                                                            Tags        = workload_tags
                                                            )

**To Reproduce**
Steps to reproduce the behavior, code snippets.

**Expected behavior**
Workload should be created

**Screenshots**
The code is failing with the below error.

  File "/usr/local/lib/python3.7/site-packages/staxapp/openapi.py", line 120, in stax_wrapper
    StaxContract.validate(payload, method_name)
  File "/usr/local/lib/python3.7/site-packages/staxapp/contract.py", line 52, in validate
    raise ValidationException(f"SCHEMA: Does not contain {component}")
staxapp.exceptions.ValidationException: SCHEMA: Does not contain workloads.CreateWorkload

**Environment Details (please complete the following information):**
 - OS: [e.g. Amazon Linux, Codebuild] MacOS
 - Python Version [e.g. 3.6, 3.7] 3.7

**Additional context**
The Catalogue creation is successful. Its only workload which is failing to create. 
I have installed staxapp using pip command.

**Comment by mat-lord** [comment]
Hi @sanjoydanversent,

Could you please send me a copy of your `schema.json` under `staxapp/data/`? 

Thanks!

**Comment by sanjoydanversent** [comment]
Hi @mat-lord ,

Here is the snippet:

        workload_client = StaxClient("workloads")
        workload_name = 'Test_WorkLoad'
        catalogue_id  = catalogue_response['CatalogueId']
        stax_account_id = "435fzzzz-yyyy-4459-413a-xxxxxx"
        region_name = 'ap-southeast-2'

        workload_parameters = []
        workload_parameters.append({'Key': 'Stage', 'Value': 'dev'})
        workload_parameters.append({'Key': 'Branch', 'Value': 'master'})

        logger.info(f'Workload Parameters : {workload_parameters}')

        workload_tags = []
        workload_tags.append({'Key': 'Stage', 'Value': 'dev'})
        workload_tags.append({'Key': 'Branch', 'Value': 'master'})

        logger.info(f'Workload Tags : {workload_tags}')
        
        workload_response = workload_client.CreateWorkload( Name        = workload_name, 
                                                            CatalogueId = catalogue_id, 
                                                            AccountId   = stax_account_id, 
                                                            Region      = region_name,
                                                            Parameters  = workload_parameters, 
                                                            Tags        = workload_tags
                                                            )

**Comment by mat-lord** [comment]
Hi @sanjoydanversent,

I'm after your local copy of this [file](https://github.com/stax-labs/lib-stax-python-sdk/blob/master/staxapp/data/schema.json).

Thanks!

**Comment by sanjoydanversent** [comment]
Hi @mat-lord ,

Please find the file.
[schema.json.gz](https://github.com/stax-labs/lib-stax-python-sdk/files/4768227/schema.json.gz)

Thanks!

**Comment by mat-lord** [comment]
Thanks @sanjoydanversent,

Can you please send me the full code (including imports) you are trying to execute?

**Comment by sanjoydanversent** [comment]
Hi @mat-lord ,

Please find the full code.

[deploy-workloads-test.py.gz](https://github.com/stax-labs/lib-stax-python-sdk/files/4768391/deploy-workloads-test.py.gz)

Thanks!

**Comment by mat-lord** [comment]
Hi @sanjoydanversent,

Looks like we've got a bug with using the local schema.

To get around this you can set `Config.load_live_schema = True` where you declared your `Config.access_key` attribute.

Let me know if this resolves your issue.

Thanks!

**Comment by mat-lord** [comment]
Live schema is now the default as per PR #45.
