### ISSUE TITLE
The 1 bug

### ISSUE THREAD

**Issue by jamesinc** [stax-labs/lib-stax-python-sdk#90]
**Describe the bug**
"1" is printed to stdout when it shouldn't be.

**To Reproduce**
make a call to staxapp.auth.ApiTokenAuth.requests_auth()

**Expected behavior**
No 1 home

**Screenshots**
I only have 1 screenshot available
![Screen Shot 2022-09-28 at 8 18 27 pm](https://user-images.githubusercontent.com/219819/192754613-6df18e77-c6dd-4e0e-ad39-8b7b966c90c9.png)

**Additional context**
This line of code is the bug: https://github.com/stax-labs/lib-stax-python-sdk/blob/master/staxapp/auth.py#L155

**Comment by richardkeit** [comment]
💚

**Comment by boltdynamics** [comment]
Thank you for raising this with us @jamesinc , this offending line has been removed as per https://github.com/stax-labs/lib-stax-python-sdk/pull/91
